# Generated by Django 4.2.16 on 2024-12-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='favteam',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
